### PR TITLE
Change of color of links, relative refresh time and more.

### PR DESCRIPTION
**Pull request by anonymous-si**
- Change of the Welcome view to display the relative time of the last refresh;
- Changed the display of information in the status bar to also display the relative time of the last refresh;
- Change of the sidebar to display the relative time of the last refresh only on iOS (iPhone);
- Changing the display of articles to increase the spacing between lines of text;
- Change the color of the links in the article view to reflect the tint color chosen by the user;
- Changing the color of the progress bar to reflect the tint color chosen by the user;
- Change the layout of the Deck view to show the scroll bars in the columns;
- Change of the date and article author view to fill in only one line of text in the Compressed view;
- Changing the article title view to fill a maximum of three lines of text in the Compressed view;
- Fixed an issue that caused the column header to be pulled down along with the list of articles in the Deck view;
- Fixed an issue that caused the progress bar to increase beyond the limit of the progress bar during a fraction of a second when progress was completed.

### CODE REVIEW

**Review by garrettrayj — APPROVED** [review]
This is great stuff! I have a few minor changes, like using the UTF-8 ellipsis character in messages, but I can handle that small stuff.  Would like to get this merged in ASAP as I'm fixing to start another round working on navigation, which always changes everything. 😄 

Congratulations on being the first contributor! It looks like you've run into a typical first contributor issue, the Xcode file with conflicts should probably be ignored.

**Comment by anonymous-si** [comment]
Thank you very much, Garrett! For me it was a pleasure to contribute to the development of an app that I like so much, and at the same time learn how to program in Swift. I hope to be able to continue to contribute with other improvements, and to be able to develop my programming skills even more.

**Comment by garrettrayj** [comment]
@anonymous-si That's great! Good ideas are always welcome around here. Good ideas with code are even more welcome!

Nice work overall, but since you're looking to level up skills I think it's only fair I mention what I changed after merge...

- Timers that start/stop when views appear/disappear. It's good to keep timers, or really any publisher not managed by SwiftUI, in-check by firing/listening only when needed.
- Consolidation of most status views into CommonStatusView. When you find yourself making a lot of duplicate code it's often easiest in the long run to consolidate into a single view, modifier, style etc.
- Duplicate relative refreshed messages in both columns didn't look/feel right. I made the sidebar display an absolute date or time depending on if it's the same day as last refresh.
- Date().formatted(...) is the modern API for formatting date objects. Absolute or relative. Ha, Den used to have a bunch of Date extensions like the one you made, but in the spirit of being bleeding edge I moved over to the new API.
- I adjusted the grid spacing in the deck layout to match the other views. In general, the grid and consistency between views is sacred ground. Also, per best practices, sizing for frames, padding, spacers, etc. should be divisible by 4.
- I reverted the 3 line limit in compressed view titles. Some of my nerdier science feeds just can't fit their titles into three lines. I did like the alignment with only 3 lines through. I'm thinking that title and teaser line-limit settings per feed may be a good feature to add.

**Comment by anonymous-si** [comment]
Thank you very much for your advice, Garrett. I was looking forward to knowing your comments about my code, so I know the points I should improve. As a beginner Swift programmer, I didn't expect to develop code the "right" way. I certainly still have a lot to learn, so I will make an effort not to make the same mistakes.

**Pull request merged**
